;this file for FamiTone2 library generated by text2data tool

TechnoHard_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,286,238
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,245,204

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env2,@env3,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c6,$cf,$cc,$c9,$c7,$c6,$c5,$c4,$c2,$00,$08
@env2:
	.byte $c3,$c7,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env3:
	.byte $c0,$c0,$bf,$bd,$00,$03


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$32,$85,$32,$85,$32,$85,$32,$85
@ref1:
	.byte $32,$85,$33,$32,$85,$32,$85,$32,$81
@ref2:
	.byte $32,$85,$32,$85,$32,$85,$32,$85
	.byte $ff,$08
	.word @ref2
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref4:
	.byte $01,$01,$01,$01,$82,$59,$01,$01,$00,$81
@ref5:
	.byte $59,$01,$01,$59,$01,$01,$01,$58,$81
@ref6:
	.byte $01,$01,$59,$01,$01,$01,$59,$00,$81
@ref7:
	.byte $59,$01,$01,$01,$59,$01,$01,$00,$81
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref8:
	.byte $80,$1b,$1b,$1b,$1b,$1b,$1b,$1b,$1a,$81
@ref9:
	.byte $1b,$1b,$1b,$1b,$1b,$1b,$1b,$1a,$81
	.byte $ff,$09
	.word @ref9
	.byte $ff,$09
	.word @ref9
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref12:
	.byte $84,$19,$1f,$19,$1f,$19,$1f,$19,$1e,$81
@ref13:
	.byte $19,$1f,$19,$19,$1f,$19,$1f,$18,$81
@ref14:
	.byte $19,$1f,$19,$1f,$19,$1f,$19,$1e,$81
	.byte $ff,$09
	.word @ref14
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref16:
	.byte $9f
@ref17:
	.byte $9f
@ref18:
	.byte $9f
@ref19:
	.byte $9f
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref20:
	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	.byte $ff,$20
	.word @ref20
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
	.byte $ff,$20
	.word @ref20
	.byte $ff,$20
	.word @ref20
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
	.byte $ff,$20
	.word @ref20
	.byte $ff,$20
	.word @ref20
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
	.byte $ff,$20
	.word @ref20
	.byte $ff,$20
	.word @ref20
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref28:
	.byte $bf
@ref29:
	.byte $bf
	.byte $fd
	.word @song1ch4loop
