;this file for FamiTone2 library generated by text2data tool

TechnoHard_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,286,238
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,245,204

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env2,@env3,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c6,$cf,$cc,$c9,$c7,$c6,$c5,$c4,$c2,$00,$08
@env2:
	.byte $c3,$c7,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env3:
	.byte $c0,$c0,$bf,$bd,$00,$03


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$32,$85,$32,$85,$32,$85,$32,$85
@ref1:
	.byte $32,$85,$33,$32,$85,$32,$85,$32,$81
@ref2:
	.byte $32,$85,$32,$85,$32,$85,$32,$85
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
	.byte $ff,$09
	.word @ref1
	.byte $ff,$08
	.word @ref2
	.byte $ff,$08
	.word @ref2
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref8:
	.byte $01,$01,$01,$01,$82,$59,$01,$01,$00,$81
@ref9:
	.byte $59,$01,$01,$59,$01,$01,$01,$58,$81
@ref10:
	.byte $01,$01,$59,$01,$01,$01,$59,$00,$81
@ref11:
	.byte $59,$01,$01,$01,$59,$01,$01,$00,$81
@ref12:
	.byte $01,$01,$01,$01,$59,$01,$01,$00,$81
	.byte $ff,$09
	.word @ref9
	.byte $ff,$09
	.word @ref10
	.byte $ff,$09
	.word @ref11
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref16:
	.byte $80,$1b,$1b,$1b,$1b,$1b,$1b,$1b,$1a,$81
@ref17:
	.byte $1b,$1b,$1b,$1b,$1b,$1b,$1b,$1a,$81
	.byte $ff,$09
	.word @ref17
	.byte $ff,$09
	.word @ref17
	.byte $ff,$09
	.word @ref17
	.byte $ff,$09
	.word @ref17
	.byte $ff,$09
	.word @ref17
@ref23:
	.byte $29,$29,$17,$17,$1f,$25,$29,$28,$81
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref24:
	.byte $84,$19,$1f,$19,$1f,$19,$1f,$19,$1e,$81
@ref25:
	.byte $19,$1f,$19,$19,$1f,$19,$1f,$18,$81
@ref26:
	.byte $19,$1f,$19,$1f,$19,$1f,$19,$1e,$81
	.byte $ff,$09
	.word @ref26
@ref28:
	.byte $19,$1f,$19,$1f,$19,$1f,$19,$1e,$18
@ref29:
	.byte $19,$1f,$19,$19,$1f,$19,$1f,$18,$1e
	.byte $ff,$09
	.word @ref26
	.byte $ff,$09
	.word @ref28
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref32:
	.byte $9f
@ref33:
	.byte $9f
@ref34:
	.byte $9f
@ref35:
	.byte $9f
@ref36:
	.byte $9f
@ref37:
	.byte $9f
@ref38:
	.byte $9f
@ref39:
	.byte $9f
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref40:
	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	.byte $ff,$20
	.word @ref40
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
	.byte $ff,$20
	.word @ref40
	.byte $ff,$20
	.word @ref40
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
	.byte $ff,$20
	.word @ref40
	.byte $ff,$20
	.word @ref40
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
	.byte $ff,$20
	.word @ref40
	.byte $ff,$20
	.word @ref40
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref48:
	.byte $bf
@ref49:
	.byte $bf
	.byte $fd
	.word @song1ch4loop
