; This file is for the FamiTone2 library and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_untitled=music_data_untitled
.endif

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $30 ; 00 : Instrument 1
	.word @env0, @env1, @env1
	.byte $00

@env0:
	.byte $cf,$7f,$00,$00
@env1:
	.byte $c0,$7f,$00,$01

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
@song0ref4:
	.byte $80
@song0ref5:
	.byte $62, $cd, $00, $cd, $58, $cd, $00, $cd, $60
@song0ref14:
	.byte $cd, $00, $cd, $54, $cd, $00, $cd, $f9, $a5, $54, $cd, $00, $cd, $5c, $cd, $00, $cd, $52, $cd, $00, $cd, $60, $cd, $00
	.byte $f9, $f3
@song0ref40:
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb
	.byte $ff, $26
	.word @song0ref5
	.byte $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $ff, $0f
	.word @song0ref40
	.byte $ff, $0f
	.word @song0ref40
	.byte $ff, $0f
	.word @song0ref40
	.byte $f9, $f9, $cb, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $ff, $0f
	.word @song0ref40
	.byte $ff, $08
	.word @song0ref4
	.byte $5c
	.byte $ff, $29
	.word @song0ref14
	.byte $f9, $f9, $cb, $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $0f
	.word @song0ref40
	.byte $ff, $0f
	.word @song0ref40
	.byte $ff, $0f
	.word @song0ref40
	.byte $f9, $f9, $cb, $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $0f
	.word @song0ref40
	.byte $ff, $0f
	.word @song0ref40
	.byte $ff, $0f
	.word @song0ref40
	.byte $f9, $f9, $cb, $fd
	.word @song0ch4loop
